import = ["~/dotfiles/alacritty/theme.toml"]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[window]
decorations = 'None'

[window.padding]
x = 0
y = 0

[scrolling]
history = 100_000
multiplier = 3

[font]
size = 10

  [font.normal]
  family = "Jetbrains Mono NF"
  style = "Regular"

  [font.bold]
  family = "Jetbrains Mono NF"
  style = "Bold"

  [font.italic]
  family = "Jetbrains Mono NF"
  style = "Italic"

  [font.bold_italic]
  family = "Jetbrains Mono NF"
  style = "Bold Italic"

