# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ $directory ](bg:#89dceb fg:#2E3440)[](fg:#89dceb bg:#f5c2e7)\
[ $git_branch$git_status ](bg:#f5c2e7 fg:#2E3440)[](fg:#f5c2e7 bg:#fab387)\
[ $c$golang$nodejs$rust ](bg:#fab387 fg:#2E3440)[](fg:#fab387)
"""
right_format = """
[ $time ](fg:#6E6466)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[directory]
format = "$path"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
format = '$symbol ($version)'

[git_branch]
symbol = ""
format = '$symbol $branch'

[git_status]
format = '$all_status$ahead_behind'

[golang]
symbol = " "
format = '$symbol ($version)'

[nodejs]
symbol = ""
format = '$symbol ($version)'

[rust]
symbol = ""
format = '$symbol ($version)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '$time'
