bass_enable=true
bass_maxgain=5
compander_enable=true
compander_granularity=2
compander_response=95.0;200.0;400.0;800.0;1600.0;3400.0;7500.0;0.466228;0;0;0;0;0;0
compander_time_freq_transforms=1
compander_timeconstant=0.22000
convolver_enable=false
convolver_file=
convolver_optimization_mode=0
convolver_waveform_edit=-80;-100;0;0;0;0
crossfeed_bs2b_fcut=700
crossfeed_bs2b_feed=60
crossfeed_enable=false
crossfeed_mode=0
ddc_enable=true
ddc_file=/home/dave/.var/app/me.timschneeberger.jdsp4linux/config/jamesdsp/temp.vdc
graphiceq_enable=false
graphiceq_param=GraphicEQ: 25 0; 40 0; 63 0; 100 0; 160 0; 250 0; 400 0; 630 0; 1000 0; 1600 0; 2500 0; 4000 0; 6300 0; 10000 0; 16000 0
liveprog_enable=false
liveprog_file=/home/dave/.var/app/me.timschneeberger.jdsp4linux/config/jamesdsp/liveprog/depthsurround.eel
master_enable=true
master_limrelease=2
master_limthreshold=0
master_postgain=0
reverb_bassboost=0.25000
reverb_decay=2.08000
reverb_delay=0.00000
reverb_enable=false
reverb_finaldry=-7.00000
reverb_finalwet=-9.00000
reverb_lfo_spin=0.70000
reverb_lfo_wander=0.30000
reverb_lpf_bass=600
reverb_lpf_damp=9000
reverb_lpf_input=18000
reverb_lpf_output=17000
reverb_osf=1
reverb_reflection_amount=0.30000
reverb_reflection_factor=1.00000
reverb_reflection_width=0.70000
reverb_wet=-8.00000
reverb_width=1.00000
stereowide_enable=true
stereowide_level=65
tone_enable=true
tone_eq=25.0;40.0;63.0;100.0;160.0;250.0;400.0;630.0;1000.0;1600.0;2500.0;4000.0;6300.0;10000.0;16000.0;5.62244;5.74659;5.45455;4.94546;4;3.49091;2.10909;1.52727;1.38182;1.38182;0.945454;0.799999;2.4;4.72727;5.16364
tone_filtertype=0
tone_interpolation=1
tube_enable=true
tube_pregain=200
